openapi: 3.0.1
info:
  title: azfun-odtapi-dev
  version: '2.0.0'
  description:
    EZWM integration API
  
  
servers:
  - description: dev 
    url: 'https://apim-odtapi-development.azure-api.net/'
  - description: uat/qa 
    url: 'https://apim-odtapi-uat.azure-api.net/'
  - description: staging 
    url: 'https://apim-odtapi-staging.azure-api.net/'
  - description: prod 
    url: 'https://apim-odtapi-prod.azure-api.net/'


tags:
  - name: EZWM
    description: The EZWM Integration API has the following methods.

paths:

  /GetPrescriptionStatus:
    post:
      operationId: getPrescriptionStatus
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.getprescriptionstatus]
        - oAuth2AuthCode: [app.ezwm.getprescriptionstatus]
      summary: Get the prescription status.
      description: Retrieve information about an prescription status
  /GetPrescriptionDetails:
  
    post:
      operationId: getPrescriptionDetails
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.getprescriptiondetails]
        - oAuth2AuthCode: [app.ezwm.getprescriptiondetails]
      summary: Get the prescription details.
      description: Retrieve information about an prescription details
  /GetPrescriptionReservationStatus:
  
    post:
      operationId: getPrescriptionReservationStatus
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.getprescriptionreservstatus]
        - oAuth2AuthCode: [app.ezwm.getprescriptionreservstatus]
      summary: Get the Prescription Reservation Status.
      description: Retrieve information about an Prescription Reservation Status
  /GetPrescriptionRealisationStatus:
  
    post:
      operationId: getPrescriptionRealisationStatus
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.getprescriptionrealisstatus]
        - oAuth2AuthCode: [app.ezwm.getprescriptionrealisstatus]
      summary: Get the Prescription Realisation Status.
      description: Retrieve information about an Prescription Realisation Status
  /GetPrescriptionRealisationResult:
    post:
      operationId: getPrescriptionRealisationResult
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.getprescriptionrealisresult]
        - oAuth2AuthCode: [app.ezwm.getprescriptionrealisresult]
      summary: Get the Prescription Realisation Result.
      description: Retrieve information about an Prescription Realisation Result
  /GetPrescriptionReservationResult:
    post:
      operationId: getPrescriptionReservationResult
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.getprescriptionreservresult]
        - oAuth2AuthCode: [app.ezwm.getprescriptionreservresult]
      summary: Get the Prescription Realisation Status.
      description: Retrieve information about an Prescription Realisation Status
  /SetPrescriptionReservation:
  
    post:
      operationId: setPrescriptionReservation
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.setprescriptionreservation]
        - oAuth2AuthCode: [app.ezwm.setprescriptionreservation]
      summary: Set the Prescription Reservation.
      description: Send information to set Prescription Reservation
  /SetPrescriptionRealisation:
 
    post:
      operationId: setPrescriptionRealisation
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.setprescriptionrealisation]
        - oAuth2AuthCode: [app.ezwm.setprescriptionrealisation]
      summary: Set the Prescription Realisation .
      description: Send information to set Prescription Realisation.
  /CancelPrescriptionReservation:
      post:
        operationId: cancelPrescriptionReservation
        tags:
        - ezwm
        security:
          - oAuth2ClientCred: [api.ezwm.cancelprescriptionreservation]
          - oAuth2AuthCode: [app.ezwm.cancelprescriptionreservation]
        summary: Cancel the Prescription Reservation.
        description: Does the cancelation of the Prescription Reservation
  /CancelPrescriptionRealisation:
  
    post:
      operationId: cancelPrescriptionRealisation
      tags:
      - ezwm
      security:
        - oAuth2ClientCred: [api.ezwm.cancelprescriptionrealisation]
        - oAuth2AuthCode: [app.ezwm.cancelprescriptionrealisation]
      summary: Get the Prescription Realisation Status.
      description: Retrieve information about an Prescription Realisation Status
components:

  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: For more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
      flows: 
        authorizationCode:
          authorizationUrl: https://cvtdevb2c.b2clogin.com/cvtdevb2c.onmicrosoft.com/{POLICY-NAME}/oauth2/v2.0/authorize
          tokenUrl: https://cvtdevb2c.b2clogin.com/cvtdevb2c.onmicrosoft.com/{POLICY-NAME}/oauth2/v2.0/token
          scopes:
            api.sukl.getevoucher: Grant consent to get e-voucher in SUKL
    
    oAuth2ClientCred:
      type: oauth2
      description: For more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow
      flows: 
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/56865670-71f8-4015-adb0-d807100feb84/oauth2/v2.0/token
          scopes:
            app.sukl.getevoucher: Grant consent to get e-voucher in SUKL
